apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: mongo-k8s
  labels:
    app: mongodb
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /mnt/k8s/mongo